from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "DNQ4lbVjujOprjJHyT4l"
fingerprint="f60cf2ff92778d5982fbfafbdf3f2d51c5d1cb03b8aeb1faffd98826219246b8"
# Create the client instance
client = Elasticsearch(
    "http://localhost:9200"
)

print(client.info())
